# Generated by Django 2.2.3 on 2020-02-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userid',
            new_name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='1@2.com', max_length=254),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
