# Generated by Django 2.2.3 on 2020-02-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200225_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.CharField(default='高三', max_length=40)),
                ('subject', models.CharField(default='英语', max_length=200)),
                ('introduce', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.CharField(default='高三', max_length=40)),
                ('subject', models.CharField(default='英语', max_length=200)),
                ('introduce', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='2020-02-26 19:00')),
                ('length', models.IntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='designs',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='selfdefinedesigns',
            name='student',
        ),
        migrations.RemoveField(
            model_name='selfdefinedesigns',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='fromuser',
        ),
        migrations.RenameField(
            model_name='studentinfos',
            old_name='student_class',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='studentinfos',
            name='student_address',
        ),
        migrations.RemoveField(
            model_name='studentinfos',
            name='student_grade',
        ),
        migrations.RemoveField(
            model_name='studentinfos',
            name='student_major',
        ),
        migrations.RemoveField(
            model_name='studentinfos',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='studentinfos',
            name='student_phone',
        ),
        migrations.RemoveField(
            model_name='teacherinfos',
            name='teacher_major',
        ),
        migrations.RemoveField(
            model_name='teacherinfos',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='teacherinfos',
            name='teacher_phone',
        ),
        migrations.RemoveField(
            model_name='teacherinfos',
            name='teacher_title',
        ),
        migrations.AddField(
            model_name='messages',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.TeacherInfos'),
        ),
        migrations.AddField(
            model_name='teacherinfos',
            name='mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherinfos',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='messages',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='AdminInfos',
        ),
        migrations.DeleteModel(
            name='Designs',
        ),
        migrations.DeleteModel(
            name='SelfDefineDesigns',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='student',
            field=models.ForeignKey(on_delete=models.SET(None), to='pages.StudentInfos'),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.TeacherInfos'),
        ),
        migrations.AddField(
            model_name='studentcourses',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.StudentInfos'),
        ),
        migrations.AddField(
            model_name='courseflow',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.TeacherCourse'),
        ),
    ]
