# Generated by Django 2.2.3 on 2020-02-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200227_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('minage', models.IntegerField(default=20)),
                ('maxage', models.IntegerField(default=65)),
                ('wages', models.IntegerField(default=7000)),
                ('education', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
