# Generated by Django 2.2.3 on 2020-02-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_recruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercourse',
            name='length',
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='time',
        ),
        migrations.AddField(
            model_name='teacherinfos',
            name='introduce',
            field=models.IntegerField(default=0, max_length=300),
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='student',
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='student',
            field=models.ManyToManyField(to='pages.StudentInfos'),
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='teacher',
            field=models.ManyToManyField(to='pages.TeacherInfos'),
        ),
    ]
