# Generated by Django 2.2.3 on 2020-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200228_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfos',
            name='grade',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
