# Generated by Django 2.2.3 on 2020-02-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200228_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fullname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
