# Generated by Django 2.2.3 on 2020-02-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200228_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfos',
            name='education',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherinfos',
            name='fee',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(default='男', max_length=10),
        ),
    ]
