# Generated by Django 2.2.3 on 2020-02-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200229_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='title',
            field=models.CharField(default='新闻公告', max_length=30),
        ),
        migrations.AlterField(
            model_name='notices',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='teacherinfos',
            name='introduce',
            field=models.CharField(default='', max_length=200),
        ),
    ]
