# Generated by Django 2.2.3 on 2020-03-01 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200229_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCourseflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.TeacherCourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.StudentInfos')),
            ],
        ),
    ]
