# Generated by Django 2.2.3 on 2020-03-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_bookcourseflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourses',
            name='introduce',
        ),
        migrations.AddField(
            model_name='bookcourseflow',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.TeacherInfos'),
        ),
        migrations.AddField(
            model_name='studentcourses',
            name='demand',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bookcourseflow',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.StudentInfos'),
        ),
    ]
