# Generated by Django 2.2.3 on 2020-03-01 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200301_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourses',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentcourses',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.StudentInfos'),
        ),
    ]
