# Generated by Django 2.2.3 on 2020-03-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20200301_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcourseflow',
            name='demand',
            field=models.CharField(default='', max_length=500),
        ),
    ]
