# Generated by Django 2.2.3 on 2020-03-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_bookcourseflow_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('grade', models.CharField(default='高三', max_length=40)),
                ('subject', models.CharField(default='英语', max_length=200)),
                ('fee', models.IntegerField(default=100)),
            ],
        ),
    ]
