# Generated by Django 2.2.3 on 2020-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='teachertype',
            field=models.CharField(default='大学生', max_length=10),
        ),
    ]
