# Generated by Django 2.2.3 on 2020-03-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_charge_teachertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseflow',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.TeacherInfos'),
        ),
        migrations.AlterField(
            model_name='courseflow',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.TeacherCourse'),
        ),
    ]
