# Generated by Django 2.2.3 on 2020-03-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200307_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='recruit',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='education',
            field=models.CharField(default='本科', max_length=40),
        ),
    ]
