# Generated by Django 2.2.3 on 2020-03-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20200307_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruit',
            old_name='wages',
            new_name='wage',
        ),
    ]
