# Generated by Django 2.2.3 on 2020-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20200307_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourses',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentcourses',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='studentcourses',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
