# Generated by Django 2.2.3 on 2020-03-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20200307_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseflow',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
