# Generated by Django 2.2.3 on 2020-03-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_courseflow_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseflow',
            name='updatetime',
        ),
    ]
