# Generated by Django 2.2.3 on 2020-03-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_remove_courseflow_updatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfos',
            name='marknum',
            field=models.IntegerField(default=0),
        ),
    ]
