# Generated by Django 2.2.3 on 2020-03-08 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_teacherinfos_marknum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcourseflow',
            name='callname',
        ),
        migrations.AddField(
            model_name='bookcourseflow',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.TeacherCourse'),
        ),
    ]
