# Generated by Django 2.2.3 on 2020-03-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20200308_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcourseflow',
            name='course',
        ),
    ]
