# Generated by Django 2.2.3 on 2020-03-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_remove_bookcourseflow_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcourseflow',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.StudentInfos'),
        ),
    ]
