# Generated by Django 2.2.3 on 2020-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_bookcourseflow_callname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcourseflow',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
