# Generated by Django 2.2.3 on 2020-03-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_bookcourseflow_marked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcourseflow',
            name='marked',
        ),
    ]
