# Generated by Django 2.2.3 on 2020-03-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_remove_bookcourseflow_marked'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
            ],
        ),
    ]
